package assignment2;

public enum ApparatusType {
    LEGPRESSMACHINE , BARBELL , HACKSQUATMACHINE , LEGEXTENSIONMACHINE , 
    LEGCURLMACHINE , LATPULLDOWNMACHINE , PECDECKMACHINE , CABLECROSSOVERMACHINE
}
